### ISSUE TITLE
Updating module name to allow easier package imports

### ISSUE THREAD

**Issue by another-rex** [G-Rath/osv-detector#149]
Extension on the package export issue #98.

Currently the module name in the `go.mod` file is `osv-detector`, which causes go get commands like:
```
go get github.com/g-rath/osv-detector/pkg/lockfile
```
to fail with the error:
```
 module declares its path as: osv-detector
       but was required as: github.com/g-rath/osv-detector
```

The workaround I'm using at the moment is to add a `replace osv-detector => github.com/g-rath/osv-detector v0.7.0` to my `go.mod` file.

Can you consider changing the module name to `github.com/g-rath/osv-detector` to allow easier `go get`ing?

**Comment by G-Rath** [comment]
Yup happy to consider this - my only concern is what impact this will have on local development; is Go able to handle the fact that the module is "within itself" so continue to act locally, or will it end up treating `github.com/g-rath/osv-detector` as an external dependency (and so I'd potentially have to wrangle different versions whenever I need to make a change that impacts multiple packages)?

(I'll also look to see if I can remove that dependency entirely for `lockfile` - I'm pretty sure its just being used for the types, which are not in that package for circular dependency reasons which I might be able to resolve another way)

**Comment by G-Rath** [comment]
🤦 ok nope it sounds like I've misunderstood how `module` works in `go.mod`: https://github.com/golang/go/issues/33274

so it should `module github.com/g-rath/osv-detector` instead of `module osv-detector`

**Comment by G-Rath** [comment]
hmm naively just changing that in `go.mod` breaks things:

```
osv-detector on  main [$!?] via 🐹 v1.17.9 via 💎 v3.1.2 took 6s
❯ make build
go build -o osv-detector
main.go:9:2: package osv-detector/internal is not in GOROOT (/home/gareth/.goenv/versions/1.17.9/src/osv-detector/internal)
main.go:10:2: package osv-detector/internal/configer is not in GOROOT (/home/gareth/.goenv/versions/1.17.9/src/osv-detector/internal/configer)
main.go:11:2: package osv-detector/internal/reporter is not in GOROOT (/home/gareth/.goenv/versions/1.17.9/src/osv-detector/internal/reporter)
main.go:12:2: package osv-detector/pkg/database is not in GOROOT (/home/gareth/.goenv/versions/1.17.9/src/osv-detector/pkg/database)
main.go:13:2: package osv-detector/pkg/lockfile is not in GOROOT (/home/gareth/.goenv/versions/1.17.9/src/osv-detector/pkg/lockfile)
make: *** [Makefile:6: build] Error 1
```

**Comment by another-rex** [comment]
In a fork earlier, I did a find and replace for `"osv-detector/` and replacing it with `"github.com/g-rath/osv-detector/` which seems to work.

**Comment by G-Rath** [comment]
Yeah I've just done that too and it seems fine: https://github.com/G-Rath/osv-detector/commit/4223de89971f9b0475b7cc0ef0ade0b4640bb024

I'll make a PR for it shortly - I'm still a little concerned about edge-cases but I'm probably just overthinking it 🤷
