### ISSUE TITLE
Support parsing pom.xml / maven / java

### ISSUE THREAD

**Issue by G-Rath** [G-Rath/osv-detector#33]
"it's just XML" - I think we should be able to have at least partial support.

In the sample I looked it, it seems you can do a sort of variable substitution which I think we shouldn't try supporting initially, but could actually land at least basic support for e.g. `properties` as a follow up

**Comment by cniweb** [comment]
+1

**Comment by G-Rath** [comment]
So I've almost finished an initial implementation for this, but realised that `pom.xml` actually isn't a lockfile so it's far less useful at this point because you only have top-level dependencies (and anything else you specify).

The issue I face is that Maven / Java is one of the few ecosystems I actually work in, so I don't even have the tools installed locally let alone know how the ecosystem feels about this to be able to know what a good path forward is here (or even if I'm missing something about how Maven works).

Overall, I think there are at least two possible paths:
  * something to do with `mvn dependency:tree`
    * I don't think I'd want the detector to support parsing this natively, but if we landed #13, people could use a script (which could live in/around this project) to transform the output from Maven into a CSV for the detector
  * something to do with https://github.com/vandmo/dependency-lock-maven-plugin
    *  again, not sure how much support I'd want to be in the detector itself but it looks like it's output as a `pom.xml` is literally a standard `pom` just with all the dependencies explicitly computed, meaning the work I've done so far should mean anyone using that will benefit - I just don't know how popular that plugin is
    * likewise after #13 is landed, it could be good to explore writing a script to transform its JSON format into a CSV. 

@cniweb is this something you'd be able to help with?

**Comment by G-Rath** [comment]
This has been released in [v0.5.0](https://github.com/G-Rath/osv-detector/releases/tag/v0.5.0)
