### ISSUE TITLE
Make lockfiles package public

### ISSUE THREAD

**Issue by oliverchang** [G-Rath/osv-detector#98]
As we discussed, I think it would be great if the `lockfiles` package was made into a public package other people could depend on and contribute to.

**Comment by oliverchang** [comment]
To me `lockfiles` makes the most sense to me, since it's a collection of different lockfile parsers.

That said, `lockfiles` probably isn't too accurate either, since this package includes parsing non-lockfile files (e.g. requirements.txt). How about `manifests`? 

Note that these don't have to go into separate repos either. You can have multiple go modules in the same repo (https://go.dev/doc/modules/managing-source#multiple-module-source) or more simply just chuck them into `pkg/` per https://github.com/golang-standards/project-layout#pkg.

**Comment by G-Rath** [comment]
> more simply just chuck them into pkg/

oh awesome - that didn't come up in my searches but it's exactly what I was hoping for as a first step since I can just chuck them in there for now.

How does it work with internal dependencies? I've got a few types sitting at the top of `internal` to avoid circular dependencies between the packages - I guess I'd have to put them into `pkg` as well? (or otherwise do some casting 🤔)

**Comment by oliverchang** [comment]
> How does it work with internal dependencies? I've got a few types sitting at the top of internal to avoid circular dependencies between the packages - I guess I'd have to put them into pkg as well? (or otherwise do some casting 🤔)

I believe you can keep things in `internal` and import them from `pkg` from the same project.

**Comment by G-Rath** [comment]
Done in #102 - I decided to stick with `lockfile` for now.

**Comment by oliverchang** [comment]
Awesome!! thank you @G-Rath :)

**Comment by G-Rath** [comment]
No problem - I've also landed the API support, which I'm planning to release sometime this weekend (just seeing if I can add support for extracting commits to a few more parsers first).

Let me know what you think should be tackled next :)
